version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rust_api
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    command: sleep infinity
    depends_on:
      - db

volumes:
  pg_data:
